### ISSUE TITLE
is your addon faster than craftsalvage() 

### ISSUE THREAD

**Issue by finegorko** [TheGeneticsGuy/Mass_Crafting_Assist#3]
i use my own addon for 1 click salvage all what i want but i need reclick it everytime

it is possible to use ur a new feature slash command in 1 macro to salvege many items

**Comment by TheGeneticsGuy** [comment]
Yes, this addon you literally will just use a slash command macro one time and it will be endless. No need to keep reclicking. This addon will keep rebuilding your stacks automatically and refreshing the crafting, thus keeping crafting endless.

Let me know if that clarifies what you were asking! Thanks!

**Comment by finegorko** [comment]
btw im noticed when u using TSM UI ur functions working

**Comment by finegorko** [comment]
and when u using TSM UI no memory leak, because DEFAULT UI spam and trigger events 'Professions.AllocationsUpdated' , this come ffrom https://github.com/Gethe/wow-ui-source/blob/02905451beb5cd7a8ef69a4c905e34af2c1e4d0e/Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafterOrderView.lua#L469

**Comment by TheGeneticsGuy** [comment]
Interesting... Thanks!
